<?php
define('Web_ID','10');
define('Web_Url','http://10.168.1.152/');
define('Up_Dir','./video/data/');
define('Up_Ext','avi|wmv|mpeg|mp4|mov|mkv|flv|f4v|m4v|rmvb|rm|mpg');
define('Zm_Dir','./video/m3u8/');
define('Zm_Preset','fast');
define('Zm_Time','1');
define('Zm_Kbps','1080k');
define('Zm_Size','');
define('Zm_Zm','0');
define('Zm_Sy','2');
define('Zm_Sylt','1:1');
define('Jpg_On','0');
define('Jpg_Num','1');
define('Jpg_Time','45');
define('Jpg_Size','320x240');
define('Api_Key','r3txhwt51rn4ppwhw5e83yb5xipp67st');
